### ISSUE TITLE
PV cannot be deleted after node was gone.

### ISSUE THREAD

**Issue by zhuangqh** [Azure/local-csi-driver#65]
## description

PV cannot be deleted after node was gone. 

## reproduce steps

Install charts from here https://github.com/kaito-project/kaito/pull/1203/files#diff-41fdd564064e869517042d47a8ccdd21dff8f4cd04cfe3f98c826e43f2e3af55.

1 create a node with nvme disk enabled.

if nodeclaim is unavailable in your cluster, you can directly create an aks nodepool

```
apiVersion: karpenter.sh/v1
kind: NodeClaim
metadata:
  name: mygpu
  labels:
    karpenter.sh/nodepool: kaito
    kaito.sh/workspace: phi-4-mini-instruct
    kaito.sh/workspacenamespace: default
    app: phi-4-mini-instruct
  annotations:
    karpenter.sh/do-not-disrupt: "true"
spec:
  taints:
    - key: "sku"
      value: "gpu"
      effect: "NoSchedule"
  nodeClassRef:
    name: gpuonly1
    kind: AKSNodeClass
    group: karpenter.azure.com
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - Standard_NC24ads_A100_v4
  - key: karpenter.sh/nodepool
    operator: In
    values:
    - kaito
  - key: gpu-provisioner.sh/machine-type
    operator: In
    values:
    - gpu
  - key: karpenter.azure.com/sku-name
    operator: In
    values:
    - Standard_NC24ads_A100_v4
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  resources:
    requests:
      storage: 500Gi
```

2 create a statefulset workload

```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-local
  labels:
    app: nginx
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  podManagementPolicy: Parallel  # default is OrderedReady
  serviceName: statefulset-local
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: statefulset-local
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(date) >> /mnt/local/outfile; sleep 1; done
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/local
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      - effect: NoSchedule
        key: sku
        operator: Equal
        value: gpu
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-nvme-disk
        resources:
          requests:
            storage: 10Gi
```

3 delete workload and delete node as well.

kubectl delete nodeclaim mygpu
After this step complete, run kubectl delete -f  example.yaml
